event_manager/event_manager/urls.py
"""
PROJECT URLs
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from drf_spectacular.views import (SpectacularAPIView, 
                                   SpectacularSwaggerView)

from rest_framework.authtoken.views import obtain_auth_token
from events.api.urls import router

urlpatterns = [
    path('admin/', admin.site.urls),

    # events/
    path('events/', include("events.urls")),
    path("", include("pages.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/events/', include(router.urls)),  # better to events/

    # cccc80546c306826f41c32d46fbcdcf7116edf8b
    path('token', obtain_auth_token, name="api-token"),
    
    # API Schema
    path('schema/', 
         SpectacularAPIView.as_view(api_version="v1"), 
         name="schema"),

    # SWAGGER UI   
    path('api/docs/', 
         SpectacularSwaggerView.as_view(url_name="schema"),
         name="swagger-ui"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

event_manager/events/api/urls.py
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
# api/category
router.register("category", views.CategoryViewSet)

event_manager/events/urls.py
""" 
EVENT URLs
"""
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [

    path("event/create", views.EventCreateView.as_view(), name="event_create"),
    path("event/<int:pk>/update", views.EventUpdateView.as_view(), name="event_update"),
    path("event/<int:pk>/delete", views.EventDeleteView.as_view(), name="event_delete"),
    
    # events (overview list of all events)
    path("", views.EventListView.as_view(), name="events"),

    # events/event/34
    path("event/<int:pk>", views.EventDetailView.as_view(), name="event_detail"),

    # events/categories (list of all Categories)
    path("categories", views.categories, name="categories"),
    path("category/<int:pk>", 
         views.category_detail, 
         name="category_detail"),
    
    # events/category/create GET or POST
    path("category/create", 
         views.category_create, 
         name="category_create"),

     # events/first
    path("first", views.first_view, name="first_view"),
]

event_manager/pages/urls.py
from django.urls import path 

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

event_manager/events/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.urls import reverse
from .validators import datetime_in_past

User = get_user_model()


class Category(models.Model):
    """a Category Model class, e.g. sport, book, hiking"""

    name = models.CharField(max_length=100, unique=True)  # VARCHAR 100

    # blank=True => Formfield can be blank
    # null=True => Database Field is nullable
    sub_title = models.CharField(
        max_length=100, null=True, blank=True)  # optional

    description = models.TextField(null=True, blank=True)  # TEXT

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def number_of_events(self) -> int:
        """returns number of events of this category."""
        return self.events.count()


class Event(models.Model):
    """describes an event in the future."""

    class Group(models.IntegerChoices):
        SMALL = 2, "small group"
        MEDIUM = 5, "medium group"
        BIG = 10, "big group"
        LARGE = 20, "large group"
        UNLIMITED = 0, "no limit"

    name = models.CharField(max_length=100, validators=[
        MinLengthValidator(3, message="Please enter at least 3 chars"),
    ])
    sub_title = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text="this is a short summary of the event.")

    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(validators=[datetime_in_past])
    is_active = models.BooleanField(default=True)  # checkbox
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="events"
    )
    # 1, 5, 10, 20, 50
    min_group = models.IntegerField(choices=Group.choices)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="events"
    )

    def get_absolute_url(self):
        return reverse("events:event_detail", kwargs={"pk": self.pk})
    
    def __str__(self) -> str:
        return self.name

event_manager/events/forms.py
""" 
in the forms.py we create the forms for the event app
"""
from django import forms 
from django.core.exceptions import ValidationError
from . import models 

class EventForm(forms.ModelForm):
    class Meta:
        model = models.Event
        # fields = "__all__"
        exclude = ("author",)

        widgets = {
            "date": forms.DateInput(
                format=("%Y-%m-%d %H:%M"), attrs={"type": "datetime-local"}
            )
        }
    
    def clean(self):
        """ 
        cross field validation: Validate two or more fields together
        """
        super().clean()  # creates the cleaned_data dict
        sub_title = self.cleaned_data.get("sub_title")
        name = self.cleaned_data.get("name")

        if sub_title == name:
            raise ValidationError(
                "Name and subtitle must not have the same value"
            )

        return self.cleaned_data

    
    def clean_sub_title(self) -> str:
        """ 
        Scheme: clean_<FIELDNAME>
        """
        sub_title = self.cleaned_data["sub_title"]
        illegal_chars = ("*", "#")
        if isinstance(sub_title, str) and sub_title.startswith(illegal_chars):
            raise ValidationError(
                "the Subtitle must not start with one of the illegal characters!"
            )
        return sub_title

        


class CategoryForm(forms.ModelForm):
    """a Modelform renders a form based on a model."""
    class Meta:
        model = models.Category
        fields = "__all__"  # must be a list OR __all__
        # fields = ("name", "sub_title")

event_manager/events/api/views.py
from rest_framework import viewsets, permissions
from rest_framework.authentication import TokenAuthentication
from events import models
from . import serializers

class CategoryViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.CategorySerializer
    queryset = models.Category.objects.prefetch_related("events", "events__author").all()

    # which kinds of Authentication we allow?
    authentication_classes = (TokenAuthentication,)  # e.g. JWT

    # which permissions are necessary?
    permission_classes = (permissions.IsAuthenticated,)

event_manager/events/views.py
import logging
from django.http import HttpRequest, HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from .models import Category, Event
from .forms import CategoryForm, EventForm

logger = logging.getLogger(__name__)

class UserIsOwnerOrAdmin(UserPassesTestMixin):

    def test_func(self) -> bool:
        # if returns True, Permission is fine. 
        # Otherwise will result in a 403 Forbidden Error
        return (self.get_object().author == self.request.user or 
                self.request.user.is_superuser)

class EventDeleteView(SuccessMessageMixin, 
                      UserIsOwnerOrAdmin, 
                      DeleteView):
    """
    generic template for confirmation page: event_confirm_delete.html
    """
    model = Event
    success_url = reverse_lazy("events:events")
    success_message = "Event was successfully deleted"


class EventUpdateView(SuccessMessageMixin, 
                      UserIsOwnerOrAdmin, 
                      UpdateView):
    model = Event
    form_class = EventForm
    success_message = "Event was successfully updated"
    

class EventCreateView(CreateView):
    model = Event
    form_class = EventForm
    # template_name = "some_other_template.html"
    # success_url = "https://amazon.com"

    def form_valid(self, form) -> HttpResponse:
        # set the author field to the current 
        # authenticated user (self.request.user)
        form.instance.author = self.request.user
        return super().form_valid(form)    


class EventDetailView(DetailView):
    model = Event

class EventListView(ListView):
    """will show all events in a list

    /events
    generic template name: event_list.html
    generic context name: object_list

    """
    model = Event
    queryset = Event.objects.select_related("category", "author").all()
    # queryset = Event.objects.prefetch_related("category", "author").all()


def categories(request):
    """ 
    Show a list of categories.
    /events/categories
    Templates have to live in templates/<APP_NAME>
    """
    categories = Category.objects.all()
    logger.warning(categories)

    return render(request, 
                  "events/category_list.html", {
                    "categories": categories,
                  })


def category_detail(request, pk):
    """ 
    Show a detail page for category
    /events/category/9
    """
    category = get_object_or_404(Category, pk=pk)

    return render(request, 
                  "events/category_detail.html", {
                    "category": category
                  })


def category_create(request):
    """Create new Category with POST data.
    
    events/category/create

    if called via GET: show Form
    if called via POST: try insert Data
    """
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            return redirect(reverse("events:category_detail", args=(category.pk,)))
        logger.warning("Wrong Form data added.")
    else:
        form = CategoryForm()
      
    return render(request, 
                  "events/category_create.html", {
                    "form": form,
                     })
      

def first_view(request: HttpRequest) -> HttpResponse:
    """
    /events/first

    each view receives a http request and has to respond
    with a HttpResponse.
    """
    print(dir(request))
    print(request.user)
    print(request.method)
    print(request.GET)
    response = HttpResponse("hello world!")
    print("Response: ", response)

    return response

event_manager/events/templates/events/category_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create new Category
{% endblock %}

{% block head %}
<a href="{% url 'events:categories' %}">
    back to Category overview
</a>
<h1>Create new Category</h1>
{% endblock %}


{% block content %}
    <form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Create Category"/>
    </form>
{% endblock %}

event_manager/events/templates/events/category_detail.html
{% extends "base.html" %}

{% block title %}
{{category}}
{% endblock %}

{% block head %}
<a href="{% url 'events:categories' %}">
    back to Category overview
</a>
<h1>{{category}}</h1>
<p>{{category.sub_title}}</p>
{% endblock %}


{% block content %}
<p>{{category.description}}</p>
{% endblock %}

event_manager/events/templates/events/category_list.html
{% extends "base.html" %}

{% block title %}
List of categories
{% endblock %}


{% block head %}
<h1>List of categories</h1>
{% endblock %}


{% block content %}
<ul>
{% if categories %}
    {% for category in categories %}
        <li>
            <a href="{% url 'events:category_detail' category.pk %}">{{category}}</a>
        </li>
    {% endfor %}
{% else %}
    <li>Sorry, no categories available</li>
{% endif %}
</ul>
{% endblock %}





{% comment %}
<!-- will not be rendered by the template engine -->
<ul>
    {% for category in categories %}
        <li>{{category}}</li>
    {% empty %}
    <li>Sorry, no categories available</li>
    {% endfor %}
</ul>
{% endcomment %}

event_manager/events/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Event: {{object.name}}
{% endblock %}

{% block head %}
<h1 class="display-6 fw-bold lh-1">Delete Event: {{object.name}}</h1>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Do you really want to delete this item: {{ object }}?</p>
        <input type="submit" class="btn btn-primary" value="Yes, please delete">
    </form>

{% endblock %}

event_manager/events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block head %}


<h1 class="display-6 fw-bold lh-1">{{object.name}}</h1>
<h3 class="display-6 lh-3">{{object.sub_title}}</h3>

<p>
at <b>{{object.date}}</b>, created by  {{object.author}}
in <a href="{% url 'events:category_detail' object.category.pk %}">
{{object.category}}</a>
</p>


{% if user.is_authenticated and user == object.author or user.is_superuser %}
<span style="font-size:12px;">
<a href="{% url 'events:event_update' object.id %}">edit</a> |
<a href="{% url 'events:event_delete' object.id %}">delete</a>
</span>
{% endif %}


{% endblock %}

{% block content %}
<div class="container">
<div class="col-lg-8 col-sm-12">

<h3>Description</h3>
<p>{{object.description}}</p>

<section class="mb-5 mt-5">
<h3>additional Infos</h3>
<ul>
  <li><b>at: {{object.date}}</b></li>
  <li>group size: {{object.get_min_group_display}}</li>
</ul>
</section>

{% comment %}
{% if object.related_events.exists %}
<section class="mb-1 mt-5">
<h3>Related Events</h3>
<ul>
  {% for related in object.related_events %}
    <li><a href="{{related.get_absolute_url}}">{{related.name}}</a></li>
  {% endfor %}
</ul>
</section>
{% endif %}
{% endcomment %}

</div>
</div>

{%endblock%}

event_manager/events/templates/events/event_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head%}

{% if object %}
    <h1>update event {{object}}</h1>
{% else %}
    <h1>add new event</h1>
{% endif %}

{% endblock %}

{% block content %}
<a href="{% url 'events:events' %}">back to Event Overview</a><br>

<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div>
    <input class="btn btn-primary" type="submit" value="Submit form" />
    </div>
</form>

{% endblock %}

event_manager/events/templates/events/event_list.html
{% extends 'base.html' %}

{% block title %}
Event Overview
{% endblock %}

{% block head%}
<h1 class="display-6 fw-bold lh-1">Overview</h1>

<p>nice Events close to you</p>
{% endblock %}

{% block content %}

<a href="{% url 'events:event_create' %}">add new event</a><br><br>

<ul class="list-group event_box">
{% for event in object_list %}

<a href="{% url 'events:event_detail' event.pk %}">
<li class="list-group-item rounded">
<small><span>am {{event.date}}</span></small><br>
<b>{{event.name}}</b>
    <span class="badge rounded-pill bg-primary">{{event.category}}</span>
    <p>by {{event.author}}</p>{{event.is_active}}
</li>
</a>

{% endfor%}
</ul>

{%endblock%}